networks:
  backend:
    driver: bridge

services:
  ## WEB SERVICE
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    build:
      context: ./nginx
      args:
        - TZ=${TZ}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ${LOG_PATH}/nginx:/var/log/nginx
      - ${SOURCE_CODE_PATH}:/var/dev
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    environment:
      - BLOG_DOMAIN=${BLOG_DOMAIN}
      - NGINX_HOST_HTTP_PORT=${NGINX_HOST_HTTP_PORT:-80}
      - NGINX_HOST_HTTPS_PORT=${NGINX_HOST_HTTPS_PORT:-443}
    networks:
      - backend
    depends_on:
      - php83

  ## BACKEND SERVICES
  php83:
    container_name: "${COMPOSE_PROJECT_NAME:-blog}-php83"
    build:
      context: php83
      args:
        - TZ=${TZ}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    networks:
      - backend
    volumes:
      - ${SOURCE_CODE_PATH}:/var/dev
    environment:
      - BLOG_DOMAIN=${BLOG_DOMAIN}
