name: Shellcheck Action

on: [ push, pull_request ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Create folder for SOURCE_CODE_PATH
        run: |
          mkdir -p ../src

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
